# coding: utf-8

"""
    Lethean Blockchain API

    OpenAPI for Lethean Blockchain

    The version of the OpenAPI document: 6.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lthn.models.db_stat_info_model import DbStatInfoModel

class TestDbStatInfoModel(unittest.TestCase):
    """DbStatInfoModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DbStatInfoModel:
        """Test DbStatInfoModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DbStatInfoModel`
        """
        model = DbStatInfoModel()
        if include_optional:
            return DbStatInfoModel(
                tx_count = 56,
                write_tx_count = 56,
                map_size = 56
            )
        else:
            return DbStatInfoModel(
        )
        """

    def testDbStatInfoModel(self):
        """Test DbStatInfoModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
