# coding: utf-8

"""
    Lethean Blockchain API

    OpenAPI for Lethean Blockchain

    The version of the OpenAPI document: 6.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lthn.models.block_template_request_model import BlockTemplateRequestModel

class TestBlockTemplateRequestModel(unittest.TestCase):
    """BlockTemplateRequestModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BlockTemplateRequestModel:
        """Test BlockTemplateRequestModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BlockTemplateRequestModel`
        """
        model = BlockTemplateRequestModel()
        if include_optional:
            return BlockTemplateRequestModel(
                miner_address = '',
                stakeholder_address = '',
                ex_nonce = '',
                pos_block = True,
                ignore_pow_ts_check = True,
                pe = lthn.models.pos_entry_model.PosEntryModel(
                    amount = 56, 
                    g_index = 56, 
                    keyimage = '', 
                    block_timestamp = 56, 
                    stake_unlock_time = 56, 
                    tx_id = '', 
                    tx_out_index = 56, 
                    wallet_index = 56, ),
                explicit_txs = [
                    ''
                    ]
            )
        else:
            return BlockTemplateRequestModel(
        )
        """

    def testBlockTemplateRequestModel(self):
        """Test BlockTemplateRequestModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
