# coding: utf-8

"""
    Lethean Blockchain API

    OpenAPI for Lethean Blockchain

    The version of the OpenAPI document: 6.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lthn.models.version_model import VersionModel

class TestVersionModel(unittest.TestCase):
    """VersionModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VersionModel:
        """Test VersionModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VersionModel`
        """
        model = VersionModel()
        if include_optional:
            return VersionModel(
                version = '',
                version_long = '',
                major = '',
                minor = '',
                revision = ''
            )
        else:
            return VersionModel(
        )
        """

    def testVersionModel(self):
        """Test VersionModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
