# coding: utf-8

"""
    Lethean Blockchain API

    OpenAPI for Lethean Blockchain

    The version of the OpenAPI document: 6.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lthn.api.block_api import BlockApi


class TestBlockApi(unittest.TestCase):
    """BlockApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BlockApi()

    def tearDown(self) -> None:
        pass

    def test_create_block_template(self) -> None:
        """Test case for create_block_template

        Create a block template for mining
        """
        pass

    def test_get_block(self) -> None:
        """Test case for get_block

        Get a block by its hash or height (ID)
        """
        pass

    def test_get_blocks(self) -> None:
        """Test case for get_blocks

        Get one or more blocks, with optional pagination.
        """
        pass

    def test_get_height(self) -> None:
        """Test case for get_height

        Get the current blockchain height
        """
        pass

    def test_submit_block(self) -> None:
        """Test case for submit_block

        Submit a new block to the network
        """
        pass


if __name__ == '__main__':
    unittest.main()
