# coding: utf-8

"""
    Lethean Blockchain API

    OpenAPI for Lethean Blockchain

    The version of the OpenAPI document: 6.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lthn.models.block_processing_performance_model import BlockProcessingPerformanceModel

class TestBlockProcessingPerformanceModel(unittest.TestCase):
    """BlockProcessingPerformanceModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BlockProcessingPerformanceModel:
        """Test BlockProcessingPerformanceModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BlockProcessingPerformanceModel`
        """
        model = BlockProcessingPerformanceModel()
        if include_optional:
            return BlockProcessingPerformanceModel(
                block_processing_time_0 = 56,
                block_processing_time_1 = 56,
                target_calculating_time_2 = 56,
                longhash_calculating_time_3 = 56,
                all_txs_insert_time_5 = 56,
                etc_stuff_6 = 56,
                insert_time_4 = 56,
                raise_block_core_event = 56,
                validate_miner_transaction_time = 56,
                collect_rangeproofs_data_from_tx_time = 56,
                verify_multiple_zc_outs_range_proofs_time = 56,
                target_calculating_enum_blocks = 56,
                target_calculating_calc = 56,
                pos_validate_ki_search = 56,
                pos_validate_get_out_keys_for_inputs = 56,
                pos_validate_zvp = 56
            )
        else:
            return BlockProcessingPerformanceModel(
        )
        """

    def testBlockProcessingPerformanceModel(self):
        """Test BlockProcessingPerformanceModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
