# coding: utf-8

"""
    Lethean Blockchain API

    OpenAPI for Lethean Blockchain

    The version of the OpenAPI document: 6.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lthn.api.info_api import InfoApi


class TestInfoApi(unittest.TestCase):
    """InfoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InfoApi()

    def tearDown(self) -> None:
        pass

    def test_get_info(self) -> None:
        """Test case for get_info

        Get detailed information about the blockchain and daemon state
        """
        pass

    def test_version(self) -> None:
        """Test case for version

        Get API version
        """
        pass


if __name__ == '__main__':
    unittest.main()
