<?php
/**
 * TxProcessingPerformanceModelTest
 *
 * PHP version 8.1
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lethean Blockchain API
 *
 * OpenAPI for Lethean Blockchain
 *
 * The version of the OpenAPI document: 6.0.1
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * TxProcessingPerformanceModelTest Class Doc Comment
 *
 * @description TxProcessingPerformanceModel
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TxProcessingPerformanceModelTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TxProcessingPerformanceModel"
     */
    public function testTxProcessingPerformanceModel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tx_check_inputs"
     */
    public function testPropertyTxCheckInputs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tx_add_one_tx"
     */
    public function testPropertyTxAddOneTx()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tx_process_extra"
     */
    public function testPropertyTxProcessExtra()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tx_process_attachment"
     */
    public function testPropertyTxProcessAttachment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tx_process_inputs"
     */
    public function testPropertyTxProcessInputs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tx_push_global_index"
     */
    public function testPropertyTxPushGlobalIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tx_check_exist"
     */
    public function testPropertyTxCheckExist()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tx_print_log"
     */
    public function testPropertyTxPrintLog()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tx_prapare_append"
     */
    public function testPropertyTxPrapareAppend()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tx_append"
     */
    public function testPropertyTxAppend()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tx_append_rl_wait"
     */
    public function testPropertyTxAppendRlWait()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tx_append_is_expired"
     */
    public function testPropertyTxAppendIsExpired()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tx_store_db"
     */
    public function testPropertyTxStoreDb()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tx_check_inputs_prefix_hash"
     */
    public function testPropertyTxCheckInputsPrefixHash()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tx_check_inputs_attachment_check"
     */
    public function testPropertyTxCheckInputsAttachmentCheck()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tx_check_inputs_loop"
     */
    public function testPropertyTxCheckInputsLoop()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tx_check_inputs_loop_kimage_check"
     */
    public function testPropertyTxCheckInputsLoopKimageCheck()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tx_check_inputs_loop_ch_in_val_sig"
     */
    public function testPropertyTxCheckInputsLoopChInValSig()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tx_check_inputs_loop_scan_outputkeys_get_item_size"
     */
    public function testPropertyTxCheckInputsLoopScanOutputkeysGetItemSize()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tx_check_inputs_loop_scan_outputkeys_relative_to_absolute"
     */
    public function testPropertyTxCheckInputsLoopScanOutputkeysRelativeToAbsolute()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tx_check_inputs_loop_scan_outputkeys_loop"
     */
    public function testPropertyTxCheckInputsLoopScanOutputkeysLoop()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tx_check_inputs_loop_scan_outputkeys_loop_get_subitem"
     */
    public function testPropertyTxCheckInputsLoopScanOutputkeysLoopGetSubitem()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tx_check_inputs_loop_scan_outputkeys_loop_find_tx"
     */
    public function testPropertyTxCheckInputsLoopScanOutputkeysLoopFindTx()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tx_check_inputs_loop_scan_outputkeys_loop_handle_output"
     */
    public function testPropertyTxCheckInputsLoopScanOutputkeysLoopHandleOutput()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tx_mixin_count"
     */
    public function testPropertyTxMixinCount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
