/*
 * Lethean Blockchain API
 * OpenAPI for Lethean Blockchain
 *
 * The version of the OpenAPI document: 6.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import invalidPackageName.JSON;

/**
 * SubmitBlockRequestModel
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-19T15:35:02.750468+01:00[Europe/London]", comments = "Generator version: 7.16.0")
public class SubmitBlockRequestModel {
  public static final String SERIALIZED_NAME_BLOCK_BLOB = "block_blob";
  @SerializedName(SERIALIZED_NAME_BLOCK_BLOB)
  @javax.annotation.Nullable
  private String blockBlob;

  public SubmitBlockRequestModel() {
  }

  public SubmitBlockRequestModel blockBlob(@javax.annotation.Nullable String blockBlob) {
    this.blockBlob = blockBlob;
    return this;
  }

  /**
   * Get blockBlob
   * @return blockBlob
   */
  @javax.annotation.Nullable
  public String getBlockBlob() {
    return blockBlob;
  }

  public void setBlockBlob(@javax.annotation.Nullable String blockBlob) {
    this.blockBlob = blockBlob;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubmitBlockRequestModel submitBlockRequestModel = (SubmitBlockRequestModel) o;
    return Objects.equals(this.blockBlob, submitBlockRequestModel.blockBlob);
  }

  @Override
  public int hashCode() {
    return Objects.hash(blockBlob);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubmitBlockRequestModel {\n");
    sb.append("    blockBlob: ").append(toIndentedString(blockBlob)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("block_blob"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SubmitBlockRequestModel
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SubmitBlockRequestModel.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in SubmitBlockRequestModel is not found in the empty JSON string", SubmitBlockRequestModel.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SubmitBlockRequestModel.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `SubmitBlockRequestModel` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("block_blob") != null && !jsonObj.get("block_blob").isJsonNull()) && !jsonObj.get("block_blob").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `block_blob` to be a primitive type in the JSON string but got `%s`", jsonObj.get("block_blob").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SubmitBlockRequestModel.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SubmitBlockRequestModel' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SubmitBlockRequestModel> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SubmitBlockRequestModel.class));

       return (TypeAdapter<T>) new TypeAdapter<SubmitBlockRequestModel>() {
           @Override
           public void write(JsonWriter out, SubmitBlockRequestModel value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SubmitBlockRequestModel read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SubmitBlockRequestModel given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SubmitBlockRequestModel
   * @throws IOException if the JSON string is invalid with respect to SubmitBlockRequestModel
   */
  public static SubmitBlockRequestModel fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SubmitBlockRequestModel.class);
  }

  /**
   * Convert an instance of SubmitBlockRequestModel to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

