/*
 * Lethean Blockchain API
 * OpenAPI for Lethean Blockchain
 *
 * The version of the OpenAPI document: 6.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Locale;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import invalidPackageName.JSON;

/**
 * TransactionExtraModel
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-19T15:35:02.750468+01:00[Europe/London]", comments = "Generator version: 7.16.0")
public class TransactionExtraModel {
  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nullable
  private String type;

  public static final String SERIALIZED_NAME_SHORT_VIEW = "short_view";
  @SerializedName(SERIALIZED_NAME_SHORT_VIEW)
  @javax.annotation.Nullable
  private String shortView;

  public static final String SERIALIZED_NAME_DETAILS_VIEW = "details_view";
  @SerializedName(SERIALIZED_NAME_DETAILS_VIEW)
  @javax.annotation.Nullable
  private String detailsView;

  public TransactionExtraModel() {
  }

  public TransactionExtraModel type(@javax.annotation.Nullable String type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nullable
  public String getType() {
    return type;
  }

  public void setType(@javax.annotation.Nullable String type) {
    this.type = type;
  }


  public TransactionExtraModel shortView(@javax.annotation.Nullable String shortView) {
    this.shortView = shortView;
    return this;
  }

  /**
   * Get shortView
   * @return shortView
   */
  @javax.annotation.Nullable
  public String getShortView() {
    return shortView;
  }

  public void setShortView(@javax.annotation.Nullable String shortView) {
    this.shortView = shortView;
  }


  public TransactionExtraModel detailsView(@javax.annotation.Nullable String detailsView) {
    this.detailsView = detailsView;
    return this;
  }

  /**
   * Get detailsView
   * @return detailsView
   */
  @javax.annotation.Nullable
  public String getDetailsView() {
    return detailsView;
  }

  public void setDetailsView(@javax.annotation.Nullable String detailsView) {
    this.detailsView = detailsView;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionExtraModel transactionExtraModel = (TransactionExtraModel) o;
    return Objects.equals(this.type, transactionExtraModel.type) &&
        Objects.equals(this.shortView, transactionExtraModel.shortView) &&
        Objects.equals(this.detailsView, transactionExtraModel.detailsView);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, shortView, detailsView);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionExtraModel {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    shortView: ").append(toIndentedString(shortView)).append("\n");
    sb.append("    detailsView: ").append(toIndentedString(detailsView)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("type", "short_view", "details_view"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TransactionExtraModel
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TransactionExtraModel.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in TransactionExtraModel is not found in the empty JSON string", TransactionExtraModel.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TransactionExtraModel.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `TransactionExtraModel` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      if ((jsonObj.get("short_view") != null && !jsonObj.get("short_view").isJsonNull()) && !jsonObj.get("short_view").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `short_view` to be a primitive type in the JSON string but got `%s`", jsonObj.get("short_view").toString()));
      }
      if ((jsonObj.get("details_view") != null && !jsonObj.get("details_view").isJsonNull()) && !jsonObj.get("details_view").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `details_view` to be a primitive type in the JSON string but got `%s`", jsonObj.get("details_view").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TransactionExtraModel.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TransactionExtraModel' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TransactionExtraModel> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TransactionExtraModel.class));

       return (TypeAdapter<T>) new TypeAdapter<TransactionExtraModel>() {
           @Override
           public void write(JsonWriter out, TransactionExtraModel value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TransactionExtraModel read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TransactionExtraModel given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TransactionExtraModel
   * @throws IOException if the JSON string is invalid with respect to TransactionExtraModel
   */
  public static TransactionExtraModel fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TransactionExtraModel.class);
  }

  /**
   * Convert an instance of TransactionExtraModel to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

