# .github/actions/upload-artifacts/action.yml
name: 'Build Documentation'
description: 'Archives and uploads signed binaries to a GitHub release'
#inputs:
#  chain-network:
#    required: true
#    description: 'The chain network name to use in filenames, mainnet or testnet'
#  assets:
#    description: "A EOL separated string list of filenames to archive; if asset is a abs path, it's respected"
#    required: false
#  asset-type:
#    required: true
#    description: 'The asset type: cli, gui, ANYTHING; used as a separator for different release packages for the same arch'
#  asset-directory:
#    required: true
#    description: "The directory where 7z's working dir will be set"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
    - uses: actions/cache@v4
      with:
        key: mkdocs-material-${{ env.cache_id }}
        path: ~/.cache
        restore-keys: |
            mkdocs-material-

    - if: runner.os == 'linux'
      run: |
        sudo apt-get install -y libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev pngquant
    - run: pip install mkdocs-git-revision-date-localized-plugin cairosvg mkdocs-git-committers-plugin-2 mkdocs-git-authors-plugin mkdocs-material[imaging]


