<?php
/**
 * BlockTemplateModel
 *
 * PHP version 8.1
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lethean Blockchain API
 *
 * OpenAPI for Lethean Blockchain
 *
 * The version of the OpenAPI document: 6.0.1
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use OpenAPI\Client\ObjectSerializer;

/**
 * BlockTemplateModel Class Doc Comment
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class BlockTemplateModel implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'BlockTemplateModel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'blocktemplate_blob' => 'string',
        'difficulty' => 'string',
        'height' => 'int',
        'miner_tx_tgc' => '\OpenAPI\Client\Model\TxGenerationContextModel',
        'block_reward_without_fee' => 'int',
        'block_reward' => 'int',
        'txs_fee' => 'int',
        'prev_hash' => 'string',
        'seed' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'blocktemplate_blob' => null,
        'difficulty' => null,
        'height' => null,
        'miner_tx_tgc' => null,
        'block_reward_without_fee' => null,
        'block_reward' => null,
        'txs_fee' => null,
        'prev_hash' => null,
        'seed' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'blocktemplate_blob' => false,
        'difficulty' => false,
        'height' => false,
        'miner_tx_tgc' => false,
        'block_reward_without_fee' => false,
        'block_reward' => false,
        'txs_fee' => false,
        'prev_hash' => false,
        'seed' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'blocktemplate_blob' => 'blocktemplate_blob',
        'difficulty' => 'difficulty',
        'height' => 'height',
        'miner_tx_tgc' => 'miner_tx_tgc',
        'block_reward_without_fee' => 'block_reward_without_fee',
        'block_reward' => 'block_reward',
        'txs_fee' => 'txs_fee',
        'prev_hash' => 'prev_hash',
        'seed' => 'seed'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'blocktemplate_blob' => 'setBlocktemplateBlob',
        'difficulty' => 'setDifficulty',
        'height' => 'setHeight',
        'miner_tx_tgc' => 'setMinerTxTgc',
        'block_reward_without_fee' => 'setBlockRewardWithoutFee',
        'block_reward' => 'setBlockReward',
        'txs_fee' => 'setTxsFee',
        'prev_hash' => 'setPrevHash',
        'seed' => 'setSeed'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'blocktemplate_blob' => 'getBlocktemplateBlob',
        'difficulty' => 'getDifficulty',
        'height' => 'getHeight',
        'miner_tx_tgc' => 'getMinerTxTgc',
        'block_reward_without_fee' => 'getBlockRewardWithoutFee',
        'block_reward' => 'getBlockReward',
        'txs_fee' => 'getTxsFee',
        'prev_hash' => 'getPrevHash',
        'seed' => 'getSeed'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('blocktemplate_blob', $data ?? [], null);
        $this->setIfExists('difficulty', $data ?? [], null);
        $this->setIfExists('height', $data ?? [], null);
        $this->setIfExists('miner_tx_tgc', $data ?? [], null);
        $this->setIfExists('block_reward_without_fee', $data ?? [], null);
        $this->setIfExists('block_reward', $data ?? [], null);
        $this->setIfExists('txs_fee', $data ?? [], null);
        $this->setIfExists('prev_hash', $data ?? [], null);
        $this->setIfExists('seed', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets blocktemplate_blob
     *
     * @return string|null
     */
    public function getBlocktemplateBlob(): ?string
    {
        return $this->container['blocktemplate_blob'];
    }

    /**
     * Sets blocktemplate_blob
     *
     * @param string|null $blocktemplate_blob blocktemplate_blob
     *
     * @return $this
     */
    public function setBlocktemplateBlob(?string $blocktemplate_blob): static
    {
        if (is_null($blocktemplate_blob)) {
            throw new InvalidArgumentException('non-nullable blocktemplate_blob cannot be null');
        }
        $this->container['blocktemplate_blob'] = $blocktemplate_blob;

        return $this;
    }

    /**
     * Gets difficulty
     *
     * @return string|null
     */
    public function getDifficulty(): ?string
    {
        return $this->container['difficulty'];
    }

    /**
     * Sets difficulty
     *
     * @param string|null $difficulty difficulty
     *
     * @return $this
     */
    public function setDifficulty(?string $difficulty): static
    {
        if (is_null($difficulty)) {
            throw new InvalidArgumentException('non-nullable difficulty cannot be null');
        }
        $this->container['difficulty'] = $difficulty;

        return $this;
    }

    /**
     * Gets height
     *
     * @return int|null
     */
    public function getHeight(): ?int
    {
        return $this->container['height'];
    }

    /**
     * Sets height
     *
     * @param int|null $height height
     *
     * @return $this
     */
    public function setHeight(?int $height): static
    {
        if (is_null($height)) {
            throw new InvalidArgumentException('non-nullable height cannot be null');
        }
        $this->container['height'] = $height;

        return $this;
    }

    /**
     * Gets miner_tx_tgc
     *
     * @return \OpenAPI\Client\Model\TxGenerationContextModel|null
     */
    public function getMinerTxTgc(): ?\OpenAPI\Client\Model\TxGenerationContextModel
    {
        return $this->container['miner_tx_tgc'];
    }

    /**
     * Sets miner_tx_tgc
     *
     * @param \OpenAPI\Client\Model\TxGenerationContextModel|null $miner_tx_tgc miner_tx_tgc
     *
     * @return $this
     */
    public function setMinerTxTgc(?\OpenAPI\Client\Model\TxGenerationContextModel $miner_tx_tgc): static
    {
        if (is_null($miner_tx_tgc)) {
            throw new InvalidArgumentException('non-nullable miner_tx_tgc cannot be null');
        }
        $this->container['miner_tx_tgc'] = $miner_tx_tgc;

        return $this;
    }

    /**
     * Gets block_reward_without_fee
     *
     * @return int|null
     */
    public function getBlockRewardWithoutFee(): ?int
    {
        return $this->container['block_reward_without_fee'];
    }

    /**
     * Sets block_reward_without_fee
     *
     * @param int|null $block_reward_without_fee block_reward_without_fee
     *
     * @return $this
     */
    public function setBlockRewardWithoutFee(?int $block_reward_without_fee): static
    {
        if (is_null($block_reward_without_fee)) {
            throw new InvalidArgumentException('non-nullable block_reward_without_fee cannot be null');
        }
        $this->container['block_reward_without_fee'] = $block_reward_without_fee;

        return $this;
    }

    /**
     * Gets block_reward
     *
     * @return int|null
     */
    public function getBlockReward(): ?int
    {
        return $this->container['block_reward'];
    }

    /**
     * Sets block_reward
     *
     * @param int|null $block_reward block_reward
     *
     * @return $this
     */
    public function setBlockReward(?int $block_reward): static
    {
        if (is_null($block_reward)) {
            throw new InvalidArgumentException('non-nullable block_reward cannot be null');
        }
        $this->container['block_reward'] = $block_reward;

        return $this;
    }

    /**
     * Gets txs_fee
     *
     * @return int|null
     */
    public function getTxsFee(): ?int
    {
        return $this->container['txs_fee'];
    }

    /**
     * Sets txs_fee
     *
     * @param int|null $txs_fee txs_fee
     *
     * @return $this
     */
    public function setTxsFee(?int $txs_fee): static
    {
        if (is_null($txs_fee)) {
            throw new InvalidArgumentException('non-nullable txs_fee cannot be null');
        }
        $this->container['txs_fee'] = $txs_fee;

        return $this;
    }

    /**
     * Gets prev_hash
     *
     * @return string|null
     */
    public function getPrevHash(): ?string
    {
        return $this->container['prev_hash'];
    }

    /**
     * Sets prev_hash
     *
     * @param string|null $prev_hash prev_hash
     *
     * @return $this
     */
    public function setPrevHash(?string $prev_hash): static
    {
        if (is_null($prev_hash)) {
            throw new InvalidArgumentException('non-nullable prev_hash cannot be null');
        }
        $this->container['prev_hash'] = $prev_hash;

        return $this;
    }

    /**
     * Gets seed
     *
     * @return string|null
     */
    public function getSeed(): ?string
    {
        return $this->container['seed'];
    }

    /**
     * Sets seed
     *
     * @param string|null $seed seed
     *
     * @return $this
     */
    public function setSeed(?string $seed): static
    {
        if (is_null($seed)) {
            throw new InvalidArgumentException('non-nullable seed cannot be null');
        }
        $this->container['seed'] = $seed;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


