<?php
/**
 * PosEntryModel
 *
 * PHP version 8.1
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lethean Blockchain API
 *
 * OpenAPI for Lethean Blockchain
 *
 * The version of the OpenAPI document: 6.0.1
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use OpenAPI\Client\ObjectSerializer;

/**
 * PosEntryModel Class Doc Comment
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class PosEntryModel implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'PosEntryModel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'amount' => 'int',
        'g_index' => 'int',
        'keyimage' => 'string',
        'block_timestamp' => 'int',
        'stake_unlock_time' => 'int',
        'tx_id' => 'string',
        'tx_out_index' => 'int',
        'wallet_index' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'amount' => null,
        'g_index' => null,
        'keyimage' => null,
        'block_timestamp' => null,
        'stake_unlock_time' => null,
        'tx_id' => null,
        'tx_out_index' => null,
        'wallet_index' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'amount' => false,
        'g_index' => false,
        'keyimage' => false,
        'block_timestamp' => false,
        'stake_unlock_time' => false,
        'tx_id' => false,
        'tx_out_index' => false,
        'wallet_index' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'amount' => 'amount',
        'g_index' => 'g_index',
        'keyimage' => 'keyimage',
        'block_timestamp' => 'block_timestamp',
        'stake_unlock_time' => 'stake_unlock_time',
        'tx_id' => 'tx_id',
        'tx_out_index' => 'tx_out_index',
        'wallet_index' => 'wallet_index'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'amount' => 'setAmount',
        'g_index' => 'setGIndex',
        'keyimage' => 'setKeyimage',
        'block_timestamp' => 'setBlockTimestamp',
        'stake_unlock_time' => 'setStakeUnlockTime',
        'tx_id' => 'setTxId',
        'tx_out_index' => 'setTxOutIndex',
        'wallet_index' => 'setWalletIndex'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'amount' => 'getAmount',
        'g_index' => 'getGIndex',
        'keyimage' => 'getKeyimage',
        'block_timestamp' => 'getBlockTimestamp',
        'stake_unlock_time' => 'getStakeUnlockTime',
        'tx_id' => 'getTxId',
        'tx_out_index' => 'getTxOutIndex',
        'wallet_index' => 'getWalletIndex'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('amount', $data ?? [], null);
        $this->setIfExists('g_index', $data ?? [], null);
        $this->setIfExists('keyimage', $data ?? [], null);
        $this->setIfExists('block_timestamp', $data ?? [], null);
        $this->setIfExists('stake_unlock_time', $data ?? [], null);
        $this->setIfExists('tx_id', $data ?? [], null);
        $this->setIfExists('tx_out_index', $data ?? [], null);
        $this->setIfExists('wallet_index', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets amount
     *
     * @return int|null
     */
    public function getAmount(): ?int
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param int|null $amount amount
     *
     * @return $this
     */
    public function setAmount(?int $amount): static
    {
        if (is_null($amount)) {
            throw new InvalidArgumentException('non-nullable amount cannot be null');
        }
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets g_index
     *
     * @return int|null
     */
    public function getGIndex(): ?int
    {
        return $this->container['g_index'];
    }

    /**
     * Sets g_index
     *
     * @param int|null $g_index g_index
     *
     * @return $this
     */
    public function setGIndex(?int $g_index): static
    {
        if (is_null($g_index)) {
            throw new InvalidArgumentException('non-nullable g_index cannot be null');
        }
        $this->container['g_index'] = $g_index;

        return $this;
    }

    /**
     * Gets keyimage
     *
     * @return string|null
     */
    public function getKeyimage(): ?string
    {
        return $this->container['keyimage'];
    }

    /**
     * Sets keyimage
     *
     * @param string|null $keyimage keyimage
     *
     * @return $this
     */
    public function setKeyimage(?string $keyimage): static
    {
        if (is_null($keyimage)) {
            throw new InvalidArgumentException('non-nullable keyimage cannot be null');
        }
        $this->container['keyimage'] = $keyimage;

        return $this;
    }

    /**
     * Gets block_timestamp
     *
     * @return int|null
     */
    public function getBlockTimestamp(): ?int
    {
        return $this->container['block_timestamp'];
    }

    /**
     * Sets block_timestamp
     *
     * @param int|null $block_timestamp block_timestamp
     *
     * @return $this
     */
    public function setBlockTimestamp(?int $block_timestamp): static
    {
        if (is_null($block_timestamp)) {
            throw new InvalidArgumentException('non-nullable block_timestamp cannot be null');
        }
        $this->container['block_timestamp'] = $block_timestamp;

        return $this;
    }

    /**
     * Gets stake_unlock_time
     *
     * @return int|null
     */
    public function getStakeUnlockTime(): ?int
    {
        return $this->container['stake_unlock_time'];
    }

    /**
     * Sets stake_unlock_time
     *
     * @param int|null $stake_unlock_time stake_unlock_time
     *
     * @return $this
     */
    public function setStakeUnlockTime(?int $stake_unlock_time): static
    {
        if (is_null($stake_unlock_time)) {
            throw new InvalidArgumentException('non-nullable stake_unlock_time cannot be null');
        }
        $this->container['stake_unlock_time'] = $stake_unlock_time;

        return $this;
    }

    /**
     * Gets tx_id
     *
     * @return string|null
     */
    public function getTxId(): ?string
    {
        return $this->container['tx_id'];
    }

    /**
     * Sets tx_id
     *
     * @param string|null $tx_id tx_id
     *
     * @return $this
     */
    public function setTxId(?string $tx_id): static
    {
        if (is_null($tx_id)) {
            throw new InvalidArgumentException('non-nullable tx_id cannot be null');
        }
        $this->container['tx_id'] = $tx_id;

        return $this;
    }

    /**
     * Gets tx_out_index
     *
     * @return int|null
     */
    public function getTxOutIndex(): ?int
    {
        return $this->container['tx_out_index'];
    }

    /**
     * Sets tx_out_index
     *
     * @param int|null $tx_out_index tx_out_index
     *
     * @return $this
     */
    public function setTxOutIndex(?int $tx_out_index): static
    {
        if (is_null($tx_out_index)) {
            throw new InvalidArgumentException('non-nullable tx_out_index cannot be null');
        }
        $this->container['tx_out_index'] = $tx_out_index;

        return $this;
    }

    /**
     * Gets wallet_index
     *
     * @return int|null
     */
    public function getWalletIndex(): ?int
    {
        return $this->container['wallet_index'];
    }

    /**
     * Sets wallet_index
     *
     * @param int|null $wallet_index wallet_index
     *
     * @return $this
     */
    public function setWalletIndex(?int $wallet_index): static
    {
        if (is_null($wallet_index)) {
            throw new InvalidArgumentException('non-nullable wallet_index cannot be null');
        }
        $this->container['wallet_index'] = $wallet_index;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


