<?php
/**
 * TxPoolPerformanceModel
 *
 * PHP version 8.1
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lethean Blockchain API
 *
 * OpenAPI for Lethean Blockchain
 *
 * The version of the OpenAPI document: 6.0.1
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use OpenAPI\Client\ObjectSerializer;

/**
 * TxPoolPerformanceModel Class Doc Comment
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class TxPoolPerformanceModel implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'TxPoolPerformanceModel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'tx_processing_time' => 'int',
        'check_inputs_types_supported_time' => 'int',
        'expiration_validate_time' => 'int',
        'validate_amount_time' => 'int',
        'validate_alias_time' => 'int',
        'check_keyimages_ws_ms_time' => 'int',
        'check_inputs_time' => 'int',
        'begin_tx_time' => 'int',
        'update_db_time' => 'int',
        'db_commit_time' => 'int',
        'check_post_hf4_balance' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'tx_processing_time' => null,
        'check_inputs_types_supported_time' => null,
        'expiration_validate_time' => null,
        'validate_amount_time' => null,
        'validate_alias_time' => null,
        'check_keyimages_ws_ms_time' => null,
        'check_inputs_time' => null,
        'begin_tx_time' => null,
        'update_db_time' => null,
        'db_commit_time' => null,
        'check_post_hf4_balance' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'tx_processing_time' => false,
        'check_inputs_types_supported_time' => false,
        'expiration_validate_time' => false,
        'validate_amount_time' => false,
        'validate_alias_time' => false,
        'check_keyimages_ws_ms_time' => false,
        'check_inputs_time' => false,
        'begin_tx_time' => false,
        'update_db_time' => false,
        'db_commit_time' => false,
        'check_post_hf4_balance' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'tx_processing_time' => 'tx_processing_time',
        'check_inputs_types_supported_time' => 'check_inputs_types_supported_time',
        'expiration_validate_time' => 'expiration_validate_time',
        'validate_amount_time' => 'validate_amount_time',
        'validate_alias_time' => 'validate_alias_time',
        'check_keyimages_ws_ms_time' => 'check_keyimages_ws_ms_time',
        'check_inputs_time' => 'check_inputs_time',
        'begin_tx_time' => 'begin_tx_time',
        'update_db_time' => 'update_db_time',
        'db_commit_time' => 'db_commit_time',
        'check_post_hf4_balance' => 'check_post_hf4_balance'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'tx_processing_time' => 'setTxProcessingTime',
        'check_inputs_types_supported_time' => 'setCheckInputsTypesSupportedTime',
        'expiration_validate_time' => 'setExpirationValidateTime',
        'validate_amount_time' => 'setValidateAmountTime',
        'validate_alias_time' => 'setValidateAliasTime',
        'check_keyimages_ws_ms_time' => 'setCheckKeyimagesWsMsTime',
        'check_inputs_time' => 'setCheckInputsTime',
        'begin_tx_time' => 'setBeginTxTime',
        'update_db_time' => 'setUpdateDbTime',
        'db_commit_time' => 'setDbCommitTime',
        'check_post_hf4_balance' => 'setCheckPostHf4Balance'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'tx_processing_time' => 'getTxProcessingTime',
        'check_inputs_types_supported_time' => 'getCheckInputsTypesSupportedTime',
        'expiration_validate_time' => 'getExpirationValidateTime',
        'validate_amount_time' => 'getValidateAmountTime',
        'validate_alias_time' => 'getValidateAliasTime',
        'check_keyimages_ws_ms_time' => 'getCheckKeyimagesWsMsTime',
        'check_inputs_time' => 'getCheckInputsTime',
        'begin_tx_time' => 'getBeginTxTime',
        'update_db_time' => 'getUpdateDbTime',
        'db_commit_time' => 'getDbCommitTime',
        'check_post_hf4_balance' => 'getCheckPostHf4Balance'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('tx_processing_time', $data ?? [], null);
        $this->setIfExists('check_inputs_types_supported_time', $data ?? [], null);
        $this->setIfExists('expiration_validate_time', $data ?? [], null);
        $this->setIfExists('validate_amount_time', $data ?? [], null);
        $this->setIfExists('validate_alias_time', $data ?? [], null);
        $this->setIfExists('check_keyimages_ws_ms_time', $data ?? [], null);
        $this->setIfExists('check_inputs_time', $data ?? [], null);
        $this->setIfExists('begin_tx_time', $data ?? [], null);
        $this->setIfExists('update_db_time', $data ?? [], null);
        $this->setIfExists('db_commit_time', $data ?? [], null);
        $this->setIfExists('check_post_hf4_balance', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets tx_processing_time
     *
     * @return int|null
     */
    public function getTxProcessingTime(): ?int
    {
        return $this->container['tx_processing_time'];
    }

    /**
     * Sets tx_processing_time
     *
     * @param int|null $tx_processing_time tx_processing_time
     *
     * @return $this
     */
    public function setTxProcessingTime(?int $tx_processing_time): static
    {
        if (is_null($tx_processing_time)) {
            throw new InvalidArgumentException('non-nullable tx_processing_time cannot be null');
        }
        $this->container['tx_processing_time'] = $tx_processing_time;

        return $this;
    }

    /**
     * Gets check_inputs_types_supported_time
     *
     * @return int|null
     */
    public function getCheckInputsTypesSupportedTime(): ?int
    {
        return $this->container['check_inputs_types_supported_time'];
    }

    /**
     * Sets check_inputs_types_supported_time
     *
     * @param int|null $check_inputs_types_supported_time check_inputs_types_supported_time
     *
     * @return $this
     */
    public function setCheckInputsTypesSupportedTime(?int $check_inputs_types_supported_time): static
    {
        if (is_null($check_inputs_types_supported_time)) {
            throw new InvalidArgumentException('non-nullable check_inputs_types_supported_time cannot be null');
        }
        $this->container['check_inputs_types_supported_time'] = $check_inputs_types_supported_time;

        return $this;
    }

    /**
     * Gets expiration_validate_time
     *
     * @return int|null
     */
    public function getExpirationValidateTime(): ?int
    {
        return $this->container['expiration_validate_time'];
    }

    /**
     * Sets expiration_validate_time
     *
     * @param int|null $expiration_validate_time expiration_validate_time
     *
     * @return $this
     */
    public function setExpirationValidateTime(?int $expiration_validate_time): static
    {
        if (is_null($expiration_validate_time)) {
            throw new InvalidArgumentException('non-nullable expiration_validate_time cannot be null');
        }
        $this->container['expiration_validate_time'] = $expiration_validate_time;

        return $this;
    }

    /**
     * Gets validate_amount_time
     *
     * @return int|null
     */
    public function getValidateAmountTime(): ?int
    {
        return $this->container['validate_amount_time'];
    }

    /**
     * Sets validate_amount_time
     *
     * @param int|null $validate_amount_time validate_amount_time
     *
     * @return $this
     */
    public function setValidateAmountTime(?int $validate_amount_time): static
    {
        if (is_null($validate_amount_time)) {
            throw new InvalidArgumentException('non-nullable validate_amount_time cannot be null');
        }
        $this->container['validate_amount_time'] = $validate_amount_time;

        return $this;
    }

    /**
     * Gets validate_alias_time
     *
     * @return int|null
     */
    public function getValidateAliasTime(): ?int
    {
        return $this->container['validate_alias_time'];
    }

    /**
     * Sets validate_alias_time
     *
     * @param int|null $validate_alias_time validate_alias_time
     *
     * @return $this
     */
    public function setValidateAliasTime(?int $validate_alias_time): static
    {
        if (is_null($validate_alias_time)) {
            throw new InvalidArgumentException('non-nullable validate_alias_time cannot be null');
        }
        $this->container['validate_alias_time'] = $validate_alias_time;

        return $this;
    }

    /**
     * Gets check_keyimages_ws_ms_time
     *
     * @return int|null
     */
    public function getCheckKeyimagesWsMsTime(): ?int
    {
        return $this->container['check_keyimages_ws_ms_time'];
    }

    /**
     * Sets check_keyimages_ws_ms_time
     *
     * @param int|null $check_keyimages_ws_ms_time check_keyimages_ws_ms_time
     *
     * @return $this
     */
    public function setCheckKeyimagesWsMsTime(?int $check_keyimages_ws_ms_time): static
    {
        if (is_null($check_keyimages_ws_ms_time)) {
            throw new InvalidArgumentException('non-nullable check_keyimages_ws_ms_time cannot be null');
        }
        $this->container['check_keyimages_ws_ms_time'] = $check_keyimages_ws_ms_time;

        return $this;
    }

    /**
     * Gets check_inputs_time
     *
     * @return int|null
     */
    public function getCheckInputsTime(): ?int
    {
        return $this->container['check_inputs_time'];
    }

    /**
     * Sets check_inputs_time
     *
     * @param int|null $check_inputs_time check_inputs_time
     *
     * @return $this
     */
    public function setCheckInputsTime(?int $check_inputs_time): static
    {
        if (is_null($check_inputs_time)) {
            throw new InvalidArgumentException('non-nullable check_inputs_time cannot be null');
        }
        $this->container['check_inputs_time'] = $check_inputs_time;

        return $this;
    }

    /**
     * Gets begin_tx_time
     *
     * @return int|null
     */
    public function getBeginTxTime(): ?int
    {
        return $this->container['begin_tx_time'];
    }

    /**
     * Sets begin_tx_time
     *
     * @param int|null $begin_tx_time begin_tx_time
     *
     * @return $this
     */
    public function setBeginTxTime(?int $begin_tx_time): static
    {
        if (is_null($begin_tx_time)) {
            throw new InvalidArgumentException('non-nullable begin_tx_time cannot be null');
        }
        $this->container['begin_tx_time'] = $begin_tx_time;

        return $this;
    }

    /**
     * Gets update_db_time
     *
     * @return int|null
     */
    public function getUpdateDbTime(): ?int
    {
        return $this->container['update_db_time'];
    }

    /**
     * Sets update_db_time
     *
     * @param int|null $update_db_time update_db_time
     *
     * @return $this
     */
    public function setUpdateDbTime(?int $update_db_time): static
    {
        if (is_null($update_db_time)) {
            throw new InvalidArgumentException('non-nullable update_db_time cannot be null');
        }
        $this->container['update_db_time'] = $update_db_time;

        return $this;
    }

    /**
     * Gets db_commit_time
     *
     * @return int|null
     */
    public function getDbCommitTime(): ?int
    {
        return $this->container['db_commit_time'];
    }

    /**
     * Sets db_commit_time
     *
     * @param int|null $db_commit_time db_commit_time
     *
     * @return $this
     */
    public function setDbCommitTime(?int $db_commit_time): static
    {
        if (is_null($db_commit_time)) {
            throw new InvalidArgumentException('non-nullable db_commit_time cannot be null');
        }
        $this->container['db_commit_time'] = $db_commit_time;

        return $this;
    }

    /**
     * Gets check_post_hf4_balance
     *
     * @return int|null
     */
    public function getCheckPostHf4Balance(): ?int
    {
        return $this->container['check_post_hf4_balance'];
    }

    /**
     * Sets check_post_hf4_balance
     *
     * @param int|null $check_post_hf4_balance check_post_hf4_balance
     *
     * @return $this
     */
    public function setCheckPostHf4Balance(?int $check_post_hf4_balance): static
    {
        if (is_null($check_post_hf4_balance)) {
            throw new InvalidArgumentException('non-nullable check_post_hf4_balance cannot be null');
        }
        $this->container['check_post_hf4_balance'] = $check_post_hf4_balance;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


