# coding: utf-8

"""
    Lethean Blockchain API

    OpenAPI for Lethean Blockchain

    The version of the OpenAPI document: 6.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class BlockProcessingPerformanceModel(BaseModel):
    """
    BlockProcessingPerformanceModel
    """ # noqa: E501
    block_processing_time_0: Optional[StrictInt] = None
    block_processing_time_1: Optional[StrictInt] = None
    target_calculating_time_2: Optional[StrictInt] = None
    longhash_calculating_time_3: Optional[StrictInt] = None
    all_txs_insert_time_5: Optional[StrictInt] = None
    etc_stuff_6: Optional[StrictInt] = None
    insert_time_4: Optional[StrictInt] = None
    raise_block_core_event: Optional[StrictInt] = None
    validate_miner_transaction_time: Optional[StrictInt] = None
    collect_rangeproofs_data_from_tx_time: Optional[StrictInt] = None
    verify_multiple_zc_outs_range_proofs_time: Optional[StrictInt] = None
    target_calculating_enum_blocks: Optional[StrictInt] = None
    target_calculating_calc: Optional[StrictInt] = None
    pos_validate_ki_search: Optional[StrictInt] = None
    pos_validate_get_out_keys_for_inputs: Optional[StrictInt] = None
    pos_validate_zvp: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["block_processing_time_0", "block_processing_time_1", "target_calculating_time_2", "longhash_calculating_time_3", "all_txs_insert_time_5", "etc_stuff_6", "insert_time_4", "raise_block_core_event", "validate_miner_transaction_time", "collect_rangeproofs_data_from_tx_time", "verify_multiple_zc_outs_range_proofs_time", "target_calculating_enum_blocks", "target_calculating_calc", "pos_validate_ki_search", "pos_validate_get_out_keys_for_inputs", "pos_validate_zvp"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BlockProcessingPerformanceModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BlockProcessingPerformanceModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "block_processing_time_0": obj.get("block_processing_time_0"),
            "block_processing_time_1": obj.get("block_processing_time_1"),
            "target_calculating_time_2": obj.get("target_calculating_time_2"),
            "longhash_calculating_time_3": obj.get("longhash_calculating_time_3"),
            "all_txs_insert_time_5": obj.get("all_txs_insert_time_5"),
            "etc_stuff_6": obj.get("etc_stuff_6"),
            "insert_time_4": obj.get("insert_time_4"),
            "raise_block_core_event": obj.get("raise_block_core_event"),
            "validate_miner_transaction_time": obj.get("validate_miner_transaction_time"),
            "collect_rangeproofs_data_from_tx_time": obj.get("collect_rangeproofs_data_from_tx_time"),
            "verify_multiple_zc_outs_range_proofs_time": obj.get("verify_multiple_zc_outs_range_proofs_time"),
            "target_calculating_enum_blocks": obj.get("target_calculating_enum_blocks"),
            "target_calculating_calc": obj.get("target_calculating_calc"),
            "pos_validate_ki_search": obj.get("pos_validate_ki_search"),
            "pos_validate_get_out_keys_for_inputs": obj.get("pos_validate_get_out_keys_for_inputs"),
            "pos_validate_zvp": obj.get("pos_validate_zvp")
        })
        return _obj


