/*
 * Lethean Blockchain API
 * OpenAPI for Lethean Blockchain
 *
 * The version of the OpenAPI document: 6.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PosEntryModel
 */
public class PosEntryModelTest {
    private final PosEntryModel model = new PosEntryModel();

    /**
     * Model tests for PosEntryModel
     */
    @Test
    public void testPosEntryModel() {
        // TODO: test PosEntryModel
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'gIndex'
     */
    @Test
    public void gIndexTest() {
        // TODO: test gIndex
    }

    /**
     * Test the property 'keyimage'
     */
    @Test
    public void keyimageTest() {
        // TODO: test keyimage
    }

    /**
     * Test the property 'blockTimestamp'
     */
    @Test
    public void blockTimestampTest() {
        // TODO: test blockTimestamp
    }

    /**
     * Test the property 'stakeUnlockTime'
     */
    @Test
    public void stakeUnlockTimeTest() {
        // TODO: test stakeUnlockTime
    }

    /**
     * Test the property 'txId'
     */
    @Test
    public void txIdTest() {
        // TODO: test txId
    }

    /**
     * Test the property 'txOutIndex'
     */
    @Test
    public void txOutIndexTest() {
        // TODO: test txOutIndex
    }

    /**
     * Test the property 'walletIndex'
     */
    @Test
    public void walletIndexTest() {
        // TODO: test walletIndex
    }

}
