/*
 * Lethean Blockchain API
 * OpenAPI for Lethean Blockchain
 *
 * The version of the OpenAPI document: 6.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TransactionAttachmentModel
 */
public class TransactionAttachmentModelTest {
    private final TransactionAttachmentModel model = new TransactionAttachmentModel();

    /**
     * Model tests for TransactionAttachmentModel
     */
    @Test
    public void testTransactionAttachmentModel() {
        // TODO: test TransactionAttachmentModel
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'shortView'
     */
    @Test
    public void shortViewTest() {
        // TODO: test shortView
    }

    /**
     * Test the property 'detailsView'
     */
    @Test
    public void detailsViewTest() {
        // TODO: test detailsView
    }

}
