/*
 * Lethean Blockchain API
 * OpenAPI for Lethean Blockchain
 *
 * The version of the OpenAPI document: 6.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.TransactionAttachmentModel;
import org.openapitools.client.model.TransactionExtraModel;
import org.openapitools.client.model.TransactionInputModel;
import org.openapitools.client.model.TransactionOutputModel;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TransactionDetailsModel
 */
public class TransactionDetailsModelTest {
    private final TransactionDetailsModel model = new TransactionDetailsModel();

    /**
     * Model tests for TransactionDetailsModel
     */
    @Test
    public void testTransactionDetailsModel() {
        // TODO: test TransactionDetailsModel
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'attachments'
     */
    @Test
    public void attachmentsTest() {
        // TODO: test attachments
    }

    /**
     * Test the property 'blob'
     */
    @Test
    public void blobTest() {
        // TODO: test blob
    }

    /**
     * Test the property 'blobSize'
     */
    @Test
    public void blobSizeTest() {
        // TODO: test blobSize
    }

    /**
     * Test the property 'extra'
     */
    @Test
    public void extraTest() {
        // TODO: test extra
    }

    /**
     * Test the property 'fee'
     */
    @Test
    public void feeTest() {
        // TODO: test fee
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'ins'
     */
    @Test
    public void insTest() {
        // TODO: test ins
    }

    /**
     * Test the property 'keeperBlock'
     */
    @Test
    public void keeperBlockTest() {
        // TODO: test keeperBlock
    }

    /**
     * Test the property 'objectInJson'
     */
    @Test
    public void objectInJsonTest() {
        // TODO: test objectInJson
    }

    /**
     * Test the property 'outs'
     */
    @Test
    public void outsTest() {
        // TODO: test outs
    }

    /**
     * Test the property 'pubKey'
     */
    @Test
    public void pubKeyTest() {
        // TODO: test pubKey
    }

    /**
     * Test the property 'timestamp'
     */
    @Test
    public void timestampTest() {
        // TODO: test timestamp
    }

}
