/*
 * Lethean Blockchain API
 * OpenAPI for Lethean Blockchain
 *
 * The version of the OpenAPI document: 6.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TransactionInputModel
 */
public class TransactionInputModelTest {
    private final TransactionInputModel model = new TransactionInputModel();

    /**
     * Model tests for TransactionInputModel
     */
    @Test
    public void testTransactionInputModel() {
        // TODO: test TransactionInputModel
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'globalIndexes'
     */
    @Test
    public void globalIndexesTest() {
        // TODO: test globalIndexes
    }

    /**
     * Test the property 'htlcOrigin'
     */
    @Test
    public void htlcOriginTest() {
        // TODO: test htlcOrigin
    }

    /**
     * Test the property 'kimageOrMsId'
     */
    @Test
    public void kimageOrMsIdTest() {
        // TODO: test kimageOrMsId
    }

    /**
     * Test the property 'multisigCount'
     */
    @Test
    public void multisigCountTest() {
        // TODO: test multisigCount
    }

}
