/**
 * Lethean Blockchain API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TxProcessingPerformanceModel { 
    tx_check_inputs?: number;
    tx_add_one_tx?: number;
    tx_process_extra?: number;
    tx_process_attachment?: number;
    tx_process_inputs?: number;
    tx_push_global_index?: number;
    tx_check_exist?: number;
    tx_print_log?: number;
    tx_prapare_append?: number;
    tx_append?: number;
    tx_append_rl_wait?: number;
    tx_append_is_expired?: number;
    tx_store_db?: number;
    tx_check_inputs_prefix_hash?: number;
    tx_check_inputs_attachment_check?: number;
    tx_check_inputs_loop?: number;
    tx_check_inputs_loop_kimage_check?: number;
    tx_check_inputs_loop_ch_in_val_sig?: number;
    tx_check_inputs_loop_scan_outputkeys_get_item_size?: number;
    tx_check_inputs_loop_scan_outputkeys_relative_to_absolute?: number;
    tx_check_inputs_loop_scan_outputkeys_loop?: number;
    tx_check_inputs_loop_scan_outputkeys_loop_get_subitem?: number;
    tx_check_inputs_loop_scan_outputkeys_loop_find_tx?: number;
    tx_check_inputs_loop_scan_outputkeys_loop_handle_output?: number;
    tx_mixin_count?: number;
}

