/**
 * Lethean Blockchain API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VersionModel { 
    version?: string;
    version_long?: string;
    major?: string;
    minor?: string;
    revision?: string;
}

