<?php
/**
 * TxGenerationContextModel
 *
 * PHP version 8.1
 *
 * @package  lthn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Lethean Blockchain API
 *
 * OpenAPI for Lethean Blockchain
 *
 * The version of the OpenAPI document: 6.0.1
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace lthn\lthn;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use lthn\ObjectSerializer;

/**
 * TxGenerationContextModel Class Doc Comment
 *
 * @package  lthn
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class TxGenerationContextModel implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'TxGenerationContextModel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'asset_ids' => 'string[]',
        'blinded_asset_ids' => 'string[]',
        'amount_commitments' => 'string[]',
        'asset_id_blinding_masks' => 'string[]',
        'amounts' => 'string[]',
        'amount_blinding_masks' => 'string[]',
        'pseudo_outs_blinded_asset_ids' => 'string[]',
        'pseudo_outs_plus_real_out_blinding_masks' => 'string[]',
        'real_zc_ins_asset_ids' => 'string[]',
        'zc_input_amounts' => 'int[]',
        'pseudo_out_amount_commitments_sum' => 'string',
        'pseudo_out_amount_blinding_masks_sum' => 'string',
        'real_in_asset_id_blinding_mask_x_amount_sum' => 'string',
        'amount_commitments_sum' => 'string',
        'amount_blinding_masks_sum' => 'string',
        'asset_id_blinding_mask_x_amount_sum' => 'string',
        'ao_asset_id' => 'string',
        'ao_asset_id_pt' => 'string',
        'ao_amount_commitment' => 'string',
        'ao_amount_blinding_mask' => 'string',
        'ao_commitment_in_outputs' => 'bool',
        'tx_key_pub' => 'string',
        'tx_key_sec' => 'string',
        'tx_pub_key_p' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'asset_ids' => null,
        'blinded_asset_ids' => null,
        'amount_commitments' => null,
        'asset_id_blinding_masks' => null,
        'amounts' => null,
        'amount_blinding_masks' => null,
        'pseudo_outs_blinded_asset_ids' => null,
        'pseudo_outs_plus_real_out_blinding_masks' => null,
        'real_zc_ins_asset_ids' => null,
        'zc_input_amounts' => null,
        'pseudo_out_amount_commitments_sum' => null,
        'pseudo_out_amount_blinding_masks_sum' => null,
        'real_in_asset_id_blinding_mask_x_amount_sum' => null,
        'amount_commitments_sum' => null,
        'amount_blinding_masks_sum' => null,
        'asset_id_blinding_mask_x_amount_sum' => null,
        'ao_asset_id' => null,
        'ao_asset_id_pt' => null,
        'ao_amount_commitment' => null,
        'ao_amount_blinding_mask' => null,
        'ao_commitment_in_outputs' => null,
        'tx_key_pub' => null,
        'tx_key_sec' => null,
        'tx_pub_key_p' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'asset_ids' => false,
        'blinded_asset_ids' => false,
        'amount_commitments' => false,
        'asset_id_blinding_masks' => false,
        'amounts' => false,
        'amount_blinding_masks' => false,
        'pseudo_outs_blinded_asset_ids' => false,
        'pseudo_outs_plus_real_out_blinding_masks' => false,
        'real_zc_ins_asset_ids' => false,
        'zc_input_amounts' => false,
        'pseudo_out_amount_commitments_sum' => false,
        'pseudo_out_amount_blinding_masks_sum' => false,
        'real_in_asset_id_blinding_mask_x_amount_sum' => false,
        'amount_commitments_sum' => false,
        'amount_blinding_masks_sum' => false,
        'asset_id_blinding_mask_x_amount_sum' => false,
        'ao_asset_id' => false,
        'ao_asset_id_pt' => false,
        'ao_amount_commitment' => false,
        'ao_amount_blinding_mask' => false,
        'ao_commitment_in_outputs' => false,
        'tx_key_pub' => false,
        'tx_key_sec' => false,
        'tx_pub_key_p' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'asset_ids' => 'asset_ids',
        'blinded_asset_ids' => 'blinded_asset_ids',
        'amount_commitments' => 'amount_commitments',
        'asset_id_blinding_masks' => 'asset_id_blinding_masks',
        'amounts' => 'amounts',
        'amount_blinding_masks' => 'amount_blinding_masks',
        'pseudo_outs_blinded_asset_ids' => 'pseudo_outs_blinded_asset_ids',
        'pseudo_outs_plus_real_out_blinding_masks' => 'pseudo_outs_plus_real_out_blinding_masks',
        'real_zc_ins_asset_ids' => 'real_zc_ins_asset_ids',
        'zc_input_amounts' => 'zc_input_amounts',
        'pseudo_out_amount_commitments_sum' => 'pseudo_out_amount_commitments_sum',
        'pseudo_out_amount_blinding_masks_sum' => 'pseudo_out_amount_blinding_masks_sum',
        'real_in_asset_id_blinding_mask_x_amount_sum' => 'real_in_asset_id_blinding_mask_x_amount_sum',
        'amount_commitments_sum' => 'amount_commitments_sum',
        'amount_blinding_masks_sum' => 'amount_blinding_masks_sum',
        'asset_id_blinding_mask_x_amount_sum' => 'asset_id_blinding_mask_x_amount_sum',
        'ao_asset_id' => 'ao_asset_id',
        'ao_asset_id_pt' => 'ao_asset_id_pt',
        'ao_amount_commitment' => 'ao_amount_commitment',
        'ao_amount_blinding_mask' => 'ao_amount_blinding_mask',
        'ao_commitment_in_outputs' => 'ao_commitment_in_outputs',
        'tx_key_pub' => 'tx_key_pub',
        'tx_key_sec' => 'tx_key_sec',
        'tx_pub_key_p' => 'tx_pub_key_p'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'asset_ids' => 'setAssetIds',
        'blinded_asset_ids' => 'setBlindedAssetIds',
        'amount_commitments' => 'setAmountCommitments',
        'asset_id_blinding_masks' => 'setAssetIdBlindingMasks',
        'amounts' => 'setAmounts',
        'amount_blinding_masks' => 'setAmountBlindingMasks',
        'pseudo_outs_blinded_asset_ids' => 'setPseudoOutsBlindedAssetIds',
        'pseudo_outs_plus_real_out_blinding_masks' => 'setPseudoOutsPlusRealOutBlindingMasks',
        'real_zc_ins_asset_ids' => 'setRealZcInsAssetIds',
        'zc_input_amounts' => 'setZcInputAmounts',
        'pseudo_out_amount_commitments_sum' => 'setPseudoOutAmountCommitmentsSum',
        'pseudo_out_amount_blinding_masks_sum' => 'setPseudoOutAmountBlindingMasksSum',
        'real_in_asset_id_blinding_mask_x_amount_sum' => 'setRealInAssetIdBlindingMaskXAmountSum',
        'amount_commitments_sum' => 'setAmountCommitmentsSum',
        'amount_blinding_masks_sum' => 'setAmountBlindingMasksSum',
        'asset_id_blinding_mask_x_amount_sum' => 'setAssetIdBlindingMaskXAmountSum',
        'ao_asset_id' => 'setAoAssetId',
        'ao_asset_id_pt' => 'setAoAssetIdPt',
        'ao_amount_commitment' => 'setAoAmountCommitment',
        'ao_amount_blinding_mask' => 'setAoAmountBlindingMask',
        'ao_commitment_in_outputs' => 'setAoCommitmentInOutputs',
        'tx_key_pub' => 'setTxKeyPub',
        'tx_key_sec' => 'setTxKeySec',
        'tx_pub_key_p' => 'setTxPubKeyP'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'asset_ids' => 'getAssetIds',
        'blinded_asset_ids' => 'getBlindedAssetIds',
        'amount_commitments' => 'getAmountCommitments',
        'asset_id_blinding_masks' => 'getAssetIdBlindingMasks',
        'amounts' => 'getAmounts',
        'amount_blinding_masks' => 'getAmountBlindingMasks',
        'pseudo_outs_blinded_asset_ids' => 'getPseudoOutsBlindedAssetIds',
        'pseudo_outs_plus_real_out_blinding_masks' => 'getPseudoOutsPlusRealOutBlindingMasks',
        'real_zc_ins_asset_ids' => 'getRealZcInsAssetIds',
        'zc_input_amounts' => 'getZcInputAmounts',
        'pseudo_out_amount_commitments_sum' => 'getPseudoOutAmountCommitmentsSum',
        'pseudo_out_amount_blinding_masks_sum' => 'getPseudoOutAmountBlindingMasksSum',
        'real_in_asset_id_blinding_mask_x_amount_sum' => 'getRealInAssetIdBlindingMaskXAmountSum',
        'amount_commitments_sum' => 'getAmountCommitmentsSum',
        'amount_blinding_masks_sum' => 'getAmountBlindingMasksSum',
        'asset_id_blinding_mask_x_amount_sum' => 'getAssetIdBlindingMaskXAmountSum',
        'ao_asset_id' => 'getAoAssetId',
        'ao_asset_id_pt' => 'getAoAssetIdPt',
        'ao_amount_commitment' => 'getAoAmountCommitment',
        'ao_amount_blinding_mask' => 'getAoAmountBlindingMask',
        'ao_commitment_in_outputs' => 'getAoCommitmentInOutputs',
        'tx_key_pub' => 'getTxKeyPub',
        'tx_key_sec' => 'getTxKeySec',
        'tx_pub_key_p' => 'getTxPubKeyP'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('asset_ids', $data ?? [], null);
        $this->setIfExists('blinded_asset_ids', $data ?? [], null);
        $this->setIfExists('amount_commitments', $data ?? [], null);
        $this->setIfExists('asset_id_blinding_masks', $data ?? [], null);
        $this->setIfExists('amounts', $data ?? [], null);
        $this->setIfExists('amount_blinding_masks', $data ?? [], null);
        $this->setIfExists('pseudo_outs_blinded_asset_ids', $data ?? [], null);
        $this->setIfExists('pseudo_outs_plus_real_out_blinding_masks', $data ?? [], null);
        $this->setIfExists('real_zc_ins_asset_ids', $data ?? [], null);
        $this->setIfExists('zc_input_amounts', $data ?? [], null);
        $this->setIfExists('pseudo_out_amount_commitments_sum', $data ?? [], null);
        $this->setIfExists('pseudo_out_amount_blinding_masks_sum', $data ?? [], null);
        $this->setIfExists('real_in_asset_id_blinding_mask_x_amount_sum', $data ?? [], null);
        $this->setIfExists('amount_commitments_sum', $data ?? [], null);
        $this->setIfExists('amount_blinding_masks_sum', $data ?? [], null);
        $this->setIfExists('asset_id_blinding_mask_x_amount_sum', $data ?? [], null);
        $this->setIfExists('ao_asset_id', $data ?? [], null);
        $this->setIfExists('ao_asset_id_pt', $data ?? [], null);
        $this->setIfExists('ao_amount_commitment', $data ?? [], null);
        $this->setIfExists('ao_amount_blinding_mask', $data ?? [], null);
        $this->setIfExists('ao_commitment_in_outputs', $data ?? [], null);
        $this->setIfExists('tx_key_pub', $data ?? [], null);
        $this->setIfExists('tx_key_sec', $data ?? [], null);
        $this->setIfExists('tx_pub_key_p', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets asset_ids
     *
     * @return string[]|null
     */
    public function getAssetIds(): ?array
    {
        return $this->container['asset_ids'];
    }

    /**
     * Sets asset_ids
     *
     * @param string[]|null $asset_ids asset_ids
     *
     * @return $this
     */
    public function setAssetIds(?array $asset_ids): static
    {
        if (is_null($asset_ids)) {
            throw new InvalidArgumentException('non-nullable asset_ids cannot be null');
        }
        $this->container['asset_ids'] = $asset_ids;

        return $this;
    }

    /**
     * Gets blinded_asset_ids
     *
     * @return string[]|null
     */
    public function getBlindedAssetIds(): ?array
    {
        return $this->container['blinded_asset_ids'];
    }

    /**
     * Sets blinded_asset_ids
     *
     * @param string[]|null $blinded_asset_ids blinded_asset_ids
     *
     * @return $this
     */
    public function setBlindedAssetIds(?array $blinded_asset_ids): static
    {
        if (is_null($blinded_asset_ids)) {
            throw new InvalidArgumentException('non-nullable blinded_asset_ids cannot be null');
        }
        $this->container['blinded_asset_ids'] = $blinded_asset_ids;

        return $this;
    }

    /**
     * Gets amount_commitments
     *
     * @return string[]|null
     */
    public function getAmountCommitments(): ?array
    {
        return $this->container['amount_commitments'];
    }

    /**
     * Sets amount_commitments
     *
     * @param string[]|null $amount_commitments amount_commitments
     *
     * @return $this
     */
    public function setAmountCommitments(?array $amount_commitments): static
    {
        if (is_null($amount_commitments)) {
            throw new InvalidArgumentException('non-nullable amount_commitments cannot be null');
        }
        $this->container['amount_commitments'] = $amount_commitments;

        return $this;
    }

    /**
     * Gets asset_id_blinding_masks
     *
     * @return string[]|null
     */
    public function getAssetIdBlindingMasks(): ?array
    {
        return $this->container['asset_id_blinding_masks'];
    }

    /**
     * Sets asset_id_blinding_masks
     *
     * @param string[]|null $asset_id_blinding_masks asset_id_blinding_masks
     *
     * @return $this
     */
    public function setAssetIdBlindingMasks(?array $asset_id_blinding_masks): static
    {
        if (is_null($asset_id_blinding_masks)) {
            throw new InvalidArgumentException('non-nullable asset_id_blinding_masks cannot be null');
        }
        $this->container['asset_id_blinding_masks'] = $asset_id_blinding_masks;

        return $this;
    }

    /**
     * Gets amounts
     *
     * @return string[]|null
     */
    public function getAmounts(): ?array
    {
        return $this->container['amounts'];
    }

    /**
     * Sets amounts
     *
     * @param string[]|null $amounts amounts
     *
     * @return $this
     */
    public function setAmounts(?array $amounts): static
    {
        if (is_null($amounts)) {
            throw new InvalidArgumentException('non-nullable amounts cannot be null');
        }
        $this->container['amounts'] = $amounts;

        return $this;
    }

    /**
     * Gets amount_blinding_masks
     *
     * @return string[]|null
     */
    public function getAmountBlindingMasks(): ?array
    {
        return $this->container['amount_blinding_masks'];
    }

    /**
     * Sets amount_blinding_masks
     *
     * @param string[]|null $amount_blinding_masks amount_blinding_masks
     *
     * @return $this
     */
    public function setAmountBlindingMasks(?array $amount_blinding_masks): static
    {
        if (is_null($amount_blinding_masks)) {
            throw new InvalidArgumentException('non-nullable amount_blinding_masks cannot be null');
        }
        $this->container['amount_blinding_masks'] = $amount_blinding_masks;

        return $this;
    }

    /**
     * Gets pseudo_outs_blinded_asset_ids
     *
     * @return string[]|null
     */
    public function getPseudoOutsBlindedAssetIds(): ?array
    {
        return $this->container['pseudo_outs_blinded_asset_ids'];
    }

    /**
     * Sets pseudo_outs_blinded_asset_ids
     *
     * @param string[]|null $pseudo_outs_blinded_asset_ids pseudo_outs_blinded_asset_ids
     *
     * @return $this
     */
    public function setPseudoOutsBlindedAssetIds(?array $pseudo_outs_blinded_asset_ids): static
    {
        if (is_null($pseudo_outs_blinded_asset_ids)) {
            throw new InvalidArgumentException('non-nullable pseudo_outs_blinded_asset_ids cannot be null');
        }
        $this->container['pseudo_outs_blinded_asset_ids'] = $pseudo_outs_blinded_asset_ids;

        return $this;
    }

    /**
     * Gets pseudo_outs_plus_real_out_blinding_masks
     *
     * @return string[]|null
     */
    public function getPseudoOutsPlusRealOutBlindingMasks(): ?array
    {
        return $this->container['pseudo_outs_plus_real_out_blinding_masks'];
    }

    /**
     * Sets pseudo_outs_plus_real_out_blinding_masks
     *
     * @param string[]|null $pseudo_outs_plus_real_out_blinding_masks pseudo_outs_plus_real_out_blinding_masks
     *
     * @return $this
     */
    public function setPseudoOutsPlusRealOutBlindingMasks(?array $pseudo_outs_plus_real_out_blinding_masks): static
    {
        if (is_null($pseudo_outs_plus_real_out_blinding_masks)) {
            throw new InvalidArgumentException('non-nullable pseudo_outs_plus_real_out_blinding_masks cannot be null');
        }
        $this->container['pseudo_outs_plus_real_out_blinding_masks'] = $pseudo_outs_plus_real_out_blinding_masks;

        return $this;
    }

    /**
     * Gets real_zc_ins_asset_ids
     *
     * @return string[]|null
     */
    public function getRealZcInsAssetIds(): ?array
    {
        return $this->container['real_zc_ins_asset_ids'];
    }

    /**
     * Sets real_zc_ins_asset_ids
     *
     * @param string[]|null $real_zc_ins_asset_ids real_zc_ins_asset_ids
     *
     * @return $this
     */
    public function setRealZcInsAssetIds(?array $real_zc_ins_asset_ids): static
    {
        if (is_null($real_zc_ins_asset_ids)) {
            throw new InvalidArgumentException('non-nullable real_zc_ins_asset_ids cannot be null');
        }
        $this->container['real_zc_ins_asset_ids'] = $real_zc_ins_asset_ids;

        return $this;
    }

    /**
     * Gets zc_input_amounts
     *
     * @return int[]|null
     */
    public function getZcInputAmounts(): ?array
    {
        return $this->container['zc_input_amounts'];
    }

    /**
     * Sets zc_input_amounts
     *
     * @param int[]|null $zc_input_amounts zc_input_amounts
     *
     * @return $this
     */
    public function setZcInputAmounts(?array $zc_input_amounts): static
    {
        if (is_null($zc_input_amounts)) {
            throw new InvalidArgumentException('non-nullable zc_input_amounts cannot be null');
        }
        $this->container['zc_input_amounts'] = $zc_input_amounts;

        return $this;
    }

    /**
     * Gets pseudo_out_amount_commitments_sum
     *
     * @return string|null
     */
    public function getPseudoOutAmountCommitmentsSum(): ?string
    {
        return $this->container['pseudo_out_amount_commitments_sum'];
    }

    /**
     * Sets pseudo_out_amount_commitments_sum
     *
     * @param string|null $pseudo_out_amount_commitments_sum pseudo_out_amount_commitments_sum
     *
     * @return $this
     */
    public function setPseudoOutAmountCommitmentsSum(?string $pseudo_out_amount_commitments_sum): static
    {
        if (is_null($pseudo_out_amount_commitments_sum)) {
            throw new InvalidArgumentException('non-nullable pseudo_out_amount_commitments_sum cannot be null');
        }
        $this->container['pseudo_out_amount_commitments_sum'] = $pseudo_out_amount_commitments_sum;

        return $this;
    }

    /**
     * Gets pseudo_out_amount_blinding_masks_sum
     *
     * @return string|null
     */
    public function getPseudoOutAmountBlindingMasksSum(): ?string
    {
        return $this->container['pseudo_out_amount_blinding_masks_sum'];
    }

    /**
     * Sets pseudo_out_amount_blinding_masks_sum
     *
     * @param string|null $pseudo_out_amount_blinding_masks_sum pseudo_out_amount_blinding_masks_sum
     *
     * @return $this
     */
    public function setPseudoOutAmountBlindingMasksSum(?string $pseudo_out_amount_blinding_masks_sum): static
    {
        if (is_null($pseudo_out_amount_blinding_masks_sum)) {
            throw new InvalidArgumentException('non-nullable pseudo_out_amount_blinding_masks_sum cannot be null');
        }
        $this->container['pseudo_out_amount_blinding_masks_sum'] = $pseudo_out_amount_blinding_masks_sum;

        return $this;
    }

    /**
     * Gets real_in_asset_id_blinding_mask_x_amount_sum
     *
     * @return string|null
     */
    public function getRealInAssetIdBlindingMaskXAmountSum(): ?string
    {
        return $this->container['real_in_asset_id_blinding_mask_x_amount_sum'];
    }

    /**
     * Sets real_in_asset_id_blinding_mask_x_amount_sum
     *
     * @param string|null $real_in_asset_id_blinding_mask_x_amount_sum real_in_asset_id_blinding_mask_x_amount_sum
     *
     * @return $this
     */
    public function setRealInAssetIdBlindingMaskXAmountSum(?string $real_in_asset_id_blinding_mask_x_amount_sum): static
    {
        if (is_null($real_in_asset_id_blinding_mask_x_amount_sum)) {
            throw new InvalidArgumentException('non-nullable real_in_asset_id_blinding_mask_x_amount_sum cannot be null');
        }
        $this->container['real_in_asset_id_blinding_mask_x_amount_sum'] = $real_in_asset_id_blinding_mask_x_amount_sum;

        return $this;
    }

    /**
     * Gets amount_commitments_sum
     *
     * @return string|null
     */
    public function getAmountCommitmentsSum(): ?string
    {
        return $this->container['amount_commitments_sum'];
    }

    /**
     * Sets amount_commitments_sum
     *
     * @param string|null $amount_commitments_sum amount_commitments_sum
     *
     * @return $this
     */
    public function setAmountCommitmentsSum(?string $amount_commitments_sum): static
    {
        if (is_null($amount_commitments_sum)) {
            throw new InvalidArgumentException('non-nullable amount_commitments_sum cannot be null');
        }
        $this->container['amount_commitments_sum'] = $amount_commitments_sum;

        return $this;
    }

    /**
     * Gets amount_blinding_masks_sum
     *
     * @return string|null
     */
    public function getAmountBlindingMasksSum(): ?string
    {
        return $this->container['amount_blinding_masks_sum'];
    }

    /**
     * Sets amount_blinding_masks_sum
     *
     * @param string|null $amount_blinding_masks_sum amount_blinding_masks_sum
     *
     * @return $this
     */
    public function setAmountBlindingMasksSum(?string $amount_blinding_masks_sum): static
    {
        if (is_null($amount_blinding_masks_sum)) {
            throw new InvalidArgumentException('non-nullable amount_blinding_masks_sum cannot be null');
        }
        $this->container['amount_blinding_masks_sum'] = $amount_blinding_masks_sum;

        return $this;
    }

    /**
     * Gets asset_id_blinding_mask_x_amount_sum
     *
     * @return string|null
     */
    public function getAssetIdBlindingMaskXAmountSum(): ?string
    {
        return $this->container['asset_id_blinding_mask_x_amount_sum'];
    }

    /**
     * Sets asset_id_blinding_mask_x_amount_sum
     *
     * @param string|null $asset_id_blinding_mask_x_amount_sum asset_id_blinding_mask_x_amount_sum
     *
     * @return $this
     */
    public function setAssetIdBlindingMaskXAmountSum(?string $asset_id_blinding_mask_x_amount_sum): static
    {
        if (is_null($asset_id_blinding_mask_x_amount_sum)) {
            throw new InvalidArgumentException('non-nullable asset_id_blinding_mask_x_amount_sum cannot be null');
        }
        $this->container['asset_id_blinding_mask_x_amount_sum'] = $asset_id_blinding_mask_x_amount_sum;

        return $this;
    }

    /**
     * Gets ao_asset_id
     *
     * @return string|null
     */
    public function getAoAssetId(): ?string
    {
        return $this->container['ao_asset_id'];
    }

    /**
     * Sets ao_asset_id
     *
     * @param string|null $ao_asset_id ao_asset_id
     *
     * @return $this
     */
    public function setAoAssetId(?string $ao_asset_id): static
    {
        if (is_null($ao_asset_id)) {
            throw new InvalidArgumentException('non-nullable ao_asset_id cannot be null');
        }
        $this->container['ao_asset_id'] = $ao_asset_id;

        return $this;
    }

    /**
     * Gets ao_asset_id_pt
     *
     * @return string|null
     */
    public function getAoAssetIdPt(): ?string
    {
        return $this->container['ao_asset_id_pt'];
    }

    /**
     * Sets ao_asset_id_pt
     *
     * @param string|null $ao_asset_id_pt ao_asset_id_pt
     *
     * @return $this
     */
    public function setAoAssetIdPt(?string $ao_asset_id_pt): static
    {
        if (is_null($ao_asset_id_pt)) {
            throw new InvalidArgumentException('non-nullable ao_asset_id_pt cannot be null');
        }
        $this->container['ao_asset_id_pt'] = $ao_asset_id_pt;

        return $this;
    }

    /**
     * Gets ao_amount_commitment
     *
     * @return string|null
     */
    public function getAoAmountCommitment(): ?string
    {
        return $this->container['ao_amount_commitment'];
    }

    /**
     * Sets ao_amount_commitment
     *
     * @param string|null $ao_amount_commitment ao_amount_commitment
     *
     * @return $this
     */
    public function setAoAmountCommitment(?string $ao_amount_commitment): static
    {
        if (is_null($ao_amount_commitment)) {
            throw new InvalidArgumentException('non-nullable ao_amount_commitment cannot be null');
        }
        $this->container['ao_amount_commitment'] = $ao_amount_commitment;

        return $this;
    }

    /**
     * Gets ao_amount_blinding_mask
     *
     * @return string|null
     */
    public function getAoAmountBlindingMask(): ?string
    {
        return $this->container['ao_amount_blinding_mask'];
    }

    /**
     * Sets ao_amount_blinding_mask
     *
     * @param string|null $ao_amount_blinding_mask ao_amount_blinding_mask
     *
     * @return $this
     */
    public function setAoAmountBlindingMask(?string $ao_amount_blinding_mask): static
    {
        if (is_null($ao_amount_blinding_mask)) {
            throw new InvalidArgumentException('non-nullable ao_amount_blinding_mask cannot be null');
        }
        $this->container['ao_amount_blinding_mask'] = $ao_amount_blinding_mask;

        return $this;
    }

    /**
     * Gets ao_commitment_in_outputs
     *
     * @return bool|null
     */
    public function getAoCommitmentInOutputs(): ?bool
    {
        return $this->container['ao_commitment_in_outputs'];
    }

    /**
     * Sets ao_commitment_in_outputs
     *
     * @param bool|null $ao_commitment_in_outputs ao_commitment_in_outputs
     *
     * @return $this
     */
    public function setAoCommitmentInOutputs(?bool $ao_commitment_in_outputs): static
    {
        if (is_null($ao_commitment_in_outputs)) {
            throw new InvalidArgumentException('non-nullable ao_commitment_in_outputs cannot be null');
        }
        $this->container['ao_commitment_in_outputs'] = $ao_commitment_in_outputs;

        return $this;
    }

    /**
     * Gets tx_key_pub
     *
     * @return string|null
     */
    public function getTxKeyPub(): ?string
    {
        return $this->container['tx_key_pub'];
    }

    /**
     * Sets tx_key_pub
     *
     * @param string|null $tx_key_pub tx_key_pub
     *
     * @return $this
     */
    public function setTxKeyPub(?string $tx_key_pub): static
    {
        if (is_null($tx_key_pub)) {
            throw new InvalidArgumentException('non-nullable tx_key_pub cannot be null');
        }
        $this->container['tx_key_pub'] = $tx_key_pub;

        return $this;
    }

    /**
     * Gets tx_key_sec
     *
     * @return string|null
     */
    public function getTxKeySec(): ?string
    {
        return $this->container['tx_key_sec'];
    }

    /**
     * Sets tx_key_sec
     *
     * @param string|null $tx_key_sec tx_key_sec
     *
     * @return $this
     */
    public function setTxKeySec(?string $tx_key_sec): static
    {
        if (is_null($tx_key_sec)) {
            throw new InvalidArgumentException('non-nullable tx_key_sec cannot be null');
        }
        $this->container['tx_key_sec'] = $tx_key_sec;

        return $this;
    }

    /**
     * Gets tx_pub_key_p
     *
     * @return string|null
     */
    public function getTxPubKeyP(): ?string
    {
        return $this->container['tx_pub_key_p'];
    }

    /**
     * Sets tx_pub_key_p
     *
     * @param string|null $tx_pub_key_p tx_pub_key_p
     *
     * @return $this
     */
    public function setTxPubKeyP(?string $tx_pub_key_p): static
    {
        if (is_null($tx_pub_key_p)) {
            throw new InvalidArgumentException('non-nullable tx_pub_key_p cannot be null');
        }
        $this->container['tx_pub_key_p'] = $tx_pub_key_p;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


