if (NOT DEFINED currency_display_decimal_point)
	message(FATAL_ERROR "currency_display_decimal_point not set")
endif()
if (NOT DEFINED currency_display_decimal_point)
	message(FATAL_ERROR "currency_display_decimal_point not set")
endif()
if (NOT DEFINED coin)
	message(FATAL_ERROR "coin not set")
endif()
if (NOT DEFINED base_reward_dust_threshold)
	message(FATAL_ERROR "base_reward_dust_threshold not set")
endif()
if (NOT DEFINED default_dust_threshold)
	message(FATAL_ERROR "default_dust_threshold not set")
endif()
if (NOT DEFINED tx_default_fee)
	message(FATAL_ERROR "tx_default_fee not set")
endif()
if (NOT DEFINED tx_minimum_fee)
	message(FATAL_ERROR "tx_minimum_fee not set")
endif()
if (NOT DEFINED difficulty_pow_starter)
	message(FATAL_ERROR "difficulty_pow_starter not set")
endif()
if (NOT DEFINED difficulty_pos_target)
	message(FATAL_ERROR "difficulty_pos_target not set")
endif()
if (NOT DEFINED difficulty_pow_target)
	message(FATAL_ERROR "difficulty_pow_target not set")
endif()
if (NOT DEFINED difficulty_window)
	message(FATAL_ERROR "difficulty_window not set")
endif()
if (NOT DEFINED difficulty_lag)
	message(FATAL_ERROR "difficulty_lag not set")
endif()
if (NOT DEFINED difficulty_cut)
	message(FATAL_ERROR "difficulty_cut not set")
endif()
if (NOT DEFINED p2p_default_port)
	message(FATAL_ERROR "p2p_default_port not set")
endif()
if (NOT DEFINED rpc_default_port)
	message(FATAL_ERROR "rpc_default_port not set")
endif()
if (NOT DEFINED stratum_default_port)
	message(FATAL_ERROR "stratum_default_port not set")
endif()
if (NOT DEFINED p2p_maintainers_pub_key)
	message(FATAL_ERROR "p2p_maintainers_pub_key not set")
endif()
if (NOT DEFINED currency_name_abr)
	message(FATAL_ERROR "currency_name_abr not set")
endif()
if (NOT DEFINED currency_name_base)
	message(FATAL_ERROR "currency_name_base not set")
endif()
if (NOT DEFINED currency_name_short_base)
	message(FATAL_ERROR "currency_name_short_base not set")
endif()
