# Tokenomics
set(coin 1000000000000 CACHE STRING "COIN" )
set(premine_amount 4000000000000000000 CACHE STRING "PREMINE_AMOUNT" )
set(tx_default_fee 10000000000 CACHE STRING "TX_DEFAULT_FEE" )
set(tx_minimum_fee 10000000000 CACHE STRING "TX_MINIMUM_FEE" )
set(currency_block_reward 1000000000000  CACHE STRING "CURRENCY_BLOCK_REWARD" )
set(currency_display_decimal_point 12 CACHE STRING "CURRENCY_DISPLAY_DECIMAL_POINT" )

# Chain Config
set(currency_name_abr "LTHN" CACHE STRING "CURRENCY_NAME_ABR" )
set(currency_name_base "Lethean" CACHE STRING "CURRENCY_NAME_BASE" )
set(currency_name_short_base "Lethean" CACHE STRING "CURRENCY_NAME_SHORT_BASE" )
set(address_prefix 0xc5 CACHE STRING "CURRENCY_PUBLIC_ADDRESS_BASE58_PREFIX" )
set(address_prefix_integrated 0x36f8 CACHE STRING "CURRENCY_PUBLIC_INTEG_ADDRESS_V2_BASE58_PREFIX" )
set(address_prefix_auditable 0x98c8  CACHE STRING "CURRENCY_PUBLIC_AUDITABLE_ADDRESS_BASE58_PREFIX" )
set(address_prefix_auditable_integrated 0x8a49  CACHE STRING "CURRENCY_PUBLIC_AUDITABLE_INTEG_ADDRESS_BASE58_PREFIX" )
set(base_reward_dust_threshold 1000000 CACHE STRING "BASE_REWARD_DUST_THRESHOLD")
set(default_dust_threshold 0 CACHE STRING "DEFAULT_DUST_THRESHOLD" )
set(difficulty_pow_starter 1 CACHE STRING "DIFFICULTY_POW_STARTER" )
set(difficulty_pos_target 120 CACHE STRING "DIFFICULTY_POS_TARGET" )
set(difficulty_pow_target 120 CACHE STRING "DIFFICULTY_POW_TARGET" )
set(difficulty_window 720 CACHE STRING "DIFFICULTY_WINDOW" )
set(difficulty_lag 15 CACHE STRING "DIFFICULTY_LAG" )
set(difficulty_cut 60 CACHE STRING "DIFFICULTY_CUT" )
set(p2p_maintainers_pub_key "8f138bb73f6d663a3746a542770781a09579a7b84cb4125249e95530824ee607" CACHE STRING "P2P_MAINTAINERS_PUB_KEY" )

if (TESTNET)
    set(p2p_default_port 36942 CACHE STRING "P2P_DEFAULT_PORT" )
    set(rpc_default_port 36941 CACHE STRING "RPC_DEFAULT_PORT" )
    set(stratum_default_port 36940 CACHE STRING "STRATUM_DEFAULT_PORT" )
else ()
    set(p2p_default_port 36942 CACHE STRING "P2P_DEFAULT_PORT" )
    set(rpc_default_port 36941 CACHE STRING "RPC_DEFAULT_PORT" )
    set(stratum_default_port 36940 CACHE STRING "STRATUM_DEFAULT_PORT" )
endif ()
