name: build-windows
permissions:
  contents: write
on:
  workflow_call:
    inputs:
      chain-network:
        description: "The network to use, can either be testnet, stagenet or mainnet"
        default: testnet
        required: false
        type: string

jobs:
  msvc-194:
    name: msvc-194-x86_64
    runs-on: windows-2022
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Cache SDK Folder
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/build/sdk
          key: ${{ runner.os }}-${{ runner.arch }}-sdk

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-git-committers-plugin-2 mkdocs-git-authors-plugin "mkdocs-material[imaging]"

      - name: Install Conan
        uses: conan-io/setup-conan@v1
        with:
          home: ${{ github.workspace }}/build/sdk
          cache_packages: true

      - name: Compile Release
        run: make release STATIC=1 CPU_CORES=4 TESTNET=${{ inputs.chain-network == 'testnet' && '1' || '0' }}

      - name: CLI Artifacts
        uses: ./.github/actions/upload-artifacts
        with:
          chain-network: ${{ inputs.chain-network }}
          assets: lethean-*
          asset-type: 'cli'
          asset-directory: ${{ github.workspace }}/build/release/packages
