name: docs
permissions:
  contents: write
on:
  workflow_call:

jobs:
  deploy:
    name: Offline Local Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Cache SDK Folder
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/build/sdk
            ${{ github.workspace }}/build/bin
          key: ${{ runner.os }}-${{ runner.arch }}-sdk

      - run: sudo apt-get install -y libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev pngquant
      - run: pip install mkdocs-git-revision-date-localized-plugin mkdocs-git-committers-plugin-2 mkdocs-git-authors-plugin mkdocs-material[imaging]

      - name: Build Offline Version
        run: make docs

      - name: CLI Artifacts
        uses: ./.github/actions/upload-artifacts
        with:
          chain-network: ${{ inputs.chain-network }}
          assets: "*"
          asset-type: 'docs'
          asset-directory: ${{ github.workspace }}/build/docs
