name: testnet-cli-macos

on:
  release:
    types:
      - published
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-project:
    name: Build Project
    runs-on: macos-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          submodules: recursive

      - name: install dependencies
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install openssl icu4c ccache miniupnpc

      - name: ccache caching
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/build/ccache
          key: ccache-testnet-cli-${{ runner.os }}

      - name: Build Boost :(
        if: steps.cache-boost.outputs.cache-hit != 'true'
        run: |
          mkdir -p build && cd build
          curl -OL https://archives.boost.io/release/1.84.0/source/boost_1_84_0.tar.bz2
          tar -xjf boost_1_84_0.tar.bz2
          rm boost_1_84_0.tar.bz2 && cd boost_1_84_0
          ./bootstrap.bat --with-libraries=system,filesystem,thread,date_time,chrono,regex,serialization,atomic,program_options,locale,timer,log
          ./b2 

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        env:
          BOOST_ROOT: ${{ github.workspace }}/build/boost_1_84_0
          CCACHE_TEMPDIR: ${{ github.workspace }}/build/ccache
          CMAKE_OSX_SYSROOT: "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.2.sdk"
        with:
          build-dir: build/release
          build-args: |
            -j2
          options: |
            TESTNET=TRUE
            CMAKE_BUILD_TYPE=Release
            CMAKE_OSX_SYSROOT=$CMAKE_OSX_SYSROOT
      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: testnet-cli-linux
          path: |
            ${{ github.workspace }}/build/release/src/Release/zanod
            ${{ github.workspace }}/build/release/src/Release/simplewallet
            ${{ github.workspace }}/build/release/src/Release/connectivity_tool
